services:
  notification-service:
    build: ./
    container_name: notification-service
    restart: always
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge